image: gitpod/workspace-full

tasks:
  - init: pip3 install -r requirements.txt
    command: python3 app.py

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
